### ISSUE TITLE
How to use it without ros?

### ISSUE THREAD

**Issue by SunPengHUST** [Hughshy/Vicon_ROS2_Bridge#1]
How to use it without ros?

**Comment by Hughshy** [comment]
copy 'src/vicon_ros2_bridge/include' and 'src/vicon_ros2_bridge/src' to your project，delete [vicon_ros2_bridge.cpp]，rewrite CMakeLists.txt by delete ROS2 dependency. RUN main.cpp so you can receive Vicon information successfully！
